export enum TYPES {
	ADD_TO_CART = "ADD_TO_CART",
	DECREMENT_ONE_FROM_CART = "DECREMENT_ONE_FROM_CART",
	INCREMENT_ONE_FROM_CART = "INCREMENT_ONE_FROM_CART",
	REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART",
	CLEAR_CART = "CLEAR_CART",
}
