// COUNTER
enum TYPESCOUNTER {
	INCREMENT = "INCREMENT",
	DECREMENT = "DECREMENT",
	INCREMENT_5 = "INCREMENT_5",
	DECREMENT_5 = "DECREMENT_5",
	RESET = "INRESET",
}

// SHOPPING CART

// CRUD

let TYPES = {
	COUNTER: TYPESCOUNTER,
};
export { TYPES };
